### ISSUE TITLE
Run directory undefined specified by model_version doesn't exist

### ISSUE THREAD

**Issue by magicaltoast** [heartexlabs/label-studio-ml-backend#82]
I am trying to run custom model without using docker compose.
This is code that I am using to launch the server. But I get an error ``model_version doesn't exist``.
```py
app = init_app(
    model_class=MyModel,
    model_dir=os.environ.get("MODEL_DIR", os.path.dirname(__file__)),
    redis_queue=os.environ.get("RQ_QUEUE_NAME", "default"),
    redis_host=os.environ.get("REDIS_HOST", "localhost"),
    redis_port=os.environ.get("REDIS_PORT", 6379),
)
if __name__ == "__main__":
    app.run(host="localhost", port=9090)
```

```
Run directory undefined specified by model_version doesn't exist
Traceback (most recent call last):
  File "/media/idk/idk1/label-studio-ml-backend/label_studio_ml/model.py", line 54, in get_result
    job_result = self.get_result_from_job_id(model_version)
  File "/media/idk/idk1/label-studio-ml-backend/label_studio_ml/model.py", line 107, in get_result_from_job_id
    result = self._get_result_from_job_id(job_id)
  File "/media/idk/idk1/label-studio-ml-backend/label_studio_ml/model.py", line 183, in _get_result_from_job_id
    raise IOError(f'Run directory {job_dir} specified by model_version doesn\'t exist')
OSError: Run directory undefined specified by model_version doesn't exist
```

**Comment by KonstantinKorotaev** [comment]
Hi @magicaltoast 
Do you have a train method in your model?
Is there a folder with model version?

**Comment by magicaltoast** [comment]
@KonstantinKorotaev 
I don't have a train method. 
Now I noticed that the ml backend is creating a folder with a timestamp as a name for each request made for my backend.

**Comment by KonstantinKorotaev** [comment]
Do you use ML backend with Label Studio or separately?

**Comment by magicaltoast** [comment]
I train it outside (not using label studio training capability). But the inference call is made by labelstudio

**Comment by KonstantinKorotaev** [comment]
Do you get predictions in your LS instance? 
It seems that you have empty version in LS, can you assign it in Project Settings?

**Comment by magicaltoast** [comment]
Yes it's working but for every reqest there is this error in terminal and new folder with current timestamp is created

**Comment by marcinz606** [comment]
I'm also getting similar error (but with current timestamp instead if `undefined`).
I have labelstudio and labelstudio (1.4.1) ml backend (1.0.5) running as deployments in GKE
`"Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/label_studio_ml/model.py", line 54, in get_result
    job_result = self.get_result_from_job_id(model_version)
  File "/usr/local/lib/python3.9/site-packages/label_studio_ml/model.py", line 107, in get_result_from_job_id
    result = self._get_result_from_job_id(job_id)
  File "/usr/local/lib/python3.9/site-packages/label_studio_ml/model.py", line 183, in _get_result_from_job_id
    raise IOError(f'Run directory {job_dir} specified by model_version doesn\'t exist')
OSError: Run directory models/1644842891 specified by model_version doesn't exist"`
`
It happens when trying to Start Training from labelstudio UI. When making POST call straight to ML backend API `/train` endpoint with labeled data & label config as json payload training runs fine

**Comment by YigitBurdurlu** [comment]
I had the same error,  solution is to downgrade label-studio to 1.4.0

`pip install label-studio==1.4.0`

**Comment by MEugeniaC** [comment]
Hello, I have the same problem. With the update to 1.4.0 this error has been solved but obtain other ModelWrapper is not itterable (in has_active_model). I have changed some part of code to solve this but the next error has been "ModelWrapper' object does not support item assignment into 'create' method of LabelStudioMLManager Class.
Note that this error only have it with ner example (ner_ml_backend.py from flair folder examples).
Can you help me, please? 
Thanks

**Comment by KonstantinKorotaev** [comment]
Hi @MEugeniaC 
Could you please checkout ML backend from [this branch](https://github.com/heartexlabs/label-studio-ml-backend/tree/DEV-1693)?

**Comment by YigitBurdurlu** [comment]
> Hi @MEugeniaC Could you please checkout ML backend from [this branch](https://github.com/heartexlabs/label-studio-ml-backend/tree/DEV-1693)?

upgrading label studio to 1.4.1 and a checkout of label studio ml backend to DEV-1693 solved the issue

**Comment by hadiyouness10** [comment]
Hello, I upgraded label studio to 1.4.1 and checkout to DEV-1693 but the error still persists...

**Comment by KonstantinKorotaev** [comment]
@hadiyouness10 
Do you mean this one:
`OSError: Run directory undefined specified by model_version doesn't exist`
?

**Comment by hadiyouness10** [comment]
yes

**Comment by YigitBurdurlu** [comment]
yes, I have the same error again

**Comment by hadiyouness10** [comment]
I checked the network from the label studio UI, it seems to be empty request:
on firefox it gives: 
status_code	401
version	"1.4.1"
detail	"Authentication credentials were not provided."
exc_info	null

On google chrome: 
{"id":"9cad8fb0-8802-4c12-8394-2c520aad2bfe","status_code":405,"version":"1.4.1","detail":"Method \"GET\" not allowed.","exc_info":null}

Is this problem? 
I don't think the request is getting properly to the backend

**Comment by KonstantinKorotaev** [comment]
> yes, I have the same error again

@YigitBurdurlu @hadiyouness10  could you please share your environment settings (LS version, ML backend version, OS, python and libs version?

> I checked the network from the label studio UI, it seems to be empty request:

@hadiyouness10 could you please describe the actions that you do in LS?

**Comment by hadiyouness10** [comment]
LS version: 1.4.1
ML Backend: checkout to dev 1693
OS Linux Ubuntu 20.04
python 3.8.10

Actions: 
1- Create a project
2- Sync images using local files (images appear in the project)
3- Import annotations using API (annotations added to each image)
4- Head to Machine learning and connect the backend (add URL --> Connects successfully backend up)
5- Press on start training --> Gives model version error

**Comment by hadiyouness10** [comment]
Issue fixed, the problem was that when encountering an error in training, it wasn't getting to the end of the fit function which returns None, and couldn't create the job_result.json file...
