### ISSUE TITLE
Error in installing label-studio-ml-backend

### ISSUE THREAD

**Issue by fer-git** [heartexlabs/label-studio-ml-backend#9]
Steps:
1. Clone this project `git clone https://github.com/heartexlabs/label-studio-ml-backend`
2. Run `cd label-studio-ml-backend`
3. Run `pip install -e .`

The error:
```
    ERROR: Command errored out with exit status 1:
     command: /home/users/miniconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/users/Projects/tutorials/label_studio/label-studio-ml-backend/setup.py'"'"'; __file__='"'"'/home/users/Projects/tutorials/label_studio/label-studio-ml-backend/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-vpaczmrj
         cwd: /home/users/Projects/tutorials/label_studio/label-studio-ml-backend/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/users/Projects/tutorials/label_studio/label-studio-ml-backend/setup.py", line 2, in <module>
        import label_studio_ml
      File "/home/users/Projects/tutorials/label_studio/label-studio-ml-backend/label_studio_ml/__init__.py", line 1, in <module>
        from .model import LabelStudioMLBase
      File "/home/users/Projects/tutorials/label_studio/label-studio-ml-backend/label_studio_ml/model.py", line 5, in <module>
        import redis
    ModuleNotFoundError: No module named 'redis'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

In setup.py, we import `label_studio_ml` on the second line, in which it will run `label-studio-ml-backend/label_studio_ml/__init__.py`, in which it ends up trying importing redis.

Isn't this circular dependency, where you need to install dependencies for label_studio_ml but you execute label_studio_ml source code?

**Comment by niklub** [comment]
Hi, @fer-git ! Thanks, fixed in 3c59ed2edfb2cfc12211fcfc3f0697385f52e6f5 Please close the issue if the problem has gone

**Comment by fer-git** [comment]
Thanks, the installation works now. But the next steps for docker-compose setup are still problematic.

1. `git clone https://github.com/heartexlabs/label-studio-ml-backend`
2. `cd label-studio-ml-backend`
3. `pip install -e .`
4. `cd label_studio_ml/examples`
5. `pip install -r requirements.txt`

These 5 steps above are fine, then the next steps are not.

1. `label-studio-ml init my-ml-backend --script label_studio-ml/examples/simple_text_classifier.py`
2. `cd my-ml-backend`
3. `docker-compose up`

I got silent error until I check `my-ml-backend/logs/uwsgi.log`. There is an error in `my-ml-backend/_wsgi.py` that requires `label_studio_ml` library. Well, `label_studio_ml` is not installed if you look at `my_ml_backend/Dockerfile`. So, I end up adding it my own.

```
RUN git clone https://github.com/heartexlabs/label-studio-ml-backend.git
WORKDIR /label-studio-ml-backend
RUN pip install -e .
RUN pip install -r label_studio_ml/examples/requirements.txt
```
I am not sure if this is the best way.

**Comment by mmartinortiz** [comment]
@fer-git 

You can replace those 4 lines for a single one:

```Dockerfile
RUN pip install https://github.com/heartexlabs/label-studio-ml-backend
```

**Comment by Mukei** [comment]
Hi,
I am having quite a similar issue.
I followed the instructions below
```shell
git clone https://github.com/heartexlabs/label-studio-ml-backend  
cd label-studio-ml-backend

# Install label-studio-ml and its dependencies
pip install -U -e .

# Install example dependencies
pip install -r label_studio_ml/examples/requirements.txt
```
The above worked without issue, but then the below failed.

```shell
label-studio-ml init my_ml_backend --script label_studio_ml/examples/substring_matching/substring_matching.py
```
or 

```shell
label-studio-ml
```

is giving me the below error
```python
Traceback (most recent call last):
  File "/Users/thomastelandro/.pyenv/versions/3.8.12/bin/label-studio-ml", line 33, in <module>
    sys.exit(load_entry_point('label-studio-ml', 'console_scripts', 'label-studio-ml')())
  File "/Users/thomastelandro/.pyenv/versions/3.8.12/bin/label-studio-ml", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/thomastelandro/.pyenv/versions/3.8.12/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Users/thomastelandro/.pyenv/versions/3.8.12/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/thomastelandro/OneDrive - UiPath/00_WIP/01-Projects/20220308-AIC-GeoTechnologies Data Extraction/01-WIP/LabelStudio/label-studio-ml-backend/label_studio_ml/server.py", line 13, in <module>
    from .model import get_all_classes_inherited_LabelStudioMLBase
  File "/Users/thomastelandro/OneDrive - UiPath/00_WIP/01-Projects/20220308-AIC-GeoTechnologies Data Extraction/01-WIP/LabelStudio/label-studio-ml-backend/label_studio_ml/model.py", line 6, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
label-studio-ml init my_ml_backend
```

Any hint on how to solve that issue?
I tried force install redis library but that didn't solve anything...

Thank you!
